FROM ubuntu:22.04

RUN apt-get update && apt-get install -y \
    gcc \
    make \
    libssl-dev \
    iproute2 \
    iputils-ping \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY . .

RUN gcc -o vport vport.c -lssl -lcrypto -Wall

CMD ["bash"]