FROM python:3.11-slim

RUN apt-get update && apt-get install -y gcc make iproute2 iputils-ping \
    && rm -rf /var/lib/apt/lists/*

RUN pip install flask PyJWT bcrypt psycopg2-binary cryptography

WORKDIR /app
COPY . .

RUN chmod +x start.sh

EXPOSE 8888/udp
EXPOSE 5000

CMD ["bash", "start.sh"]
